### ISSUE TITLE
ui: terminal is not adjusting height to available space

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#1]
### What is the URL of the page with the issue?

http://localhost:4000/using-go-modules/

### What is your user agent?

<pre>
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.23 Safari/537.36
</pre>

### Screenshot

![oversize_terminal](https://user-images.githubusercontent.com/3374574/80333983-ba6d4400-8847-11ea-83a6-fb8c6b7a1585.png)

### What did you do?

Opened the modules guide

### What did you expect to see?

The terminal sized correctly, width and height

### What did you see instead?

The terminal is too tall for the available space, causing the page scrollbar (outlined in red in the screenshot) to appear. The terminal and guide scrollbars (outlined in green) should appear, but the page scrollbar should not.

**Comment by myitcv** [comment]
Thanks for this fix.

On Linux at least, this doesn't appear to work properly unless the browser itself is the full screen height:

![bad_scroll](https://user-images.githubusercontent.com/3374574/97853040-79228900-1cef-11eb-9e08-dd8a0c275c69.png)

Notice how the page scrollbar is visible on the RHS.

**Comment by myitcv** [comment]
Looks like we might need something like https://css-tricks.com/the-trick-to-viewport-units-on-mobile/

**Comment by marcosnils** [comment]
> On Linux at least, this doesn't appear to work properly unless the browser itself is the full screen height:

Hmm just checked and seems like it happens when you resize the screen size to a smaller viewport. In my case, if I start with a small windows and resize it to make it larger it works ok, but as soon as I shrink it, the right scrollbar appears. I'll take another look.
