### ISSUE TITLE
ui: provide some visual feedback that command block has been run/upload succeeded

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#126]
Consider the following screenshot:

<img width="1304" alt="Screen Shot 2020-10-07 at 10 41 14" src="https://user-images.githubusercontent.com/3374574/95314840-aebb8a00-0889-11eb-9aa2-655660e06884.png">

On the left hand side there is no visual indication that we have "completed" the first command block. It is hard to see, at a glance, where we are progress-wise.

How about doing something like this:

<img width="1291" alt="Screen Shot 2020-10-07 at 10 46 46" src="https://user-images.githubusercontent.com/3374574/95315548-8aac7880-088a-11eb-8010-7a5f1924ba72.png">

The background and text would "dim" and a check icon be shown when the commands have executed (i.e. been sent to the terminal) or the file has successfully been uploaded.

cc @marcosnils for thoughts.

**Comment by myitcv** [comment]
Perhaps this should also prevent a click of a block that is not "next", changing the cursor to "blocked" icon or some such

**Comment by marcosnils** [comment]
We just ageed that clicking a step will not prevent from being clicked again. It's just a visual hint that the step has been executed.
