### ISSUE TITLE
ui: provide feedback on file upload

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#127]
Related to #126, we should give some visual indication within a terminal that a file has been uploaded. 

Consider:

<img width="1275" alt="Screen Shot 2020-10-07 at 10 50 51" src="https://user-images.githubusercontent.com/3374574/95315885-fdb5ef00-088a-11eb-8bfb-663ef83c5a5a.png">

There is no way of knowing (from looking at the terminal) whether we have clicked the upload block, or when it happened.

#126 discusses a means by which we can feedback which steps have been clicked, but I think we also need to feedback to the user in the terminal when this happens too.

The simplest way of achieving this would be to send a command to the target terminal once the upload has completed. However, given it logically doesn't make much sense to run a command, we can instead send a comment, something like:

```
# successfully uploaded /home/gopher/readme.txt
```

I suspect this will require some changes in the SDK, unless we want to move to a model of `preguide` generating the command/code blocks (which would give us a bit more flexibility here)

cc @marcosnils

**Comment by marcosnils** [comment]
This is already handled by #169

**Comment by myitcv** [comment]
I just tried out #169 

* I clicked on a file block (which was successful) but that didn't result in any comment in the terminal
* I then killed PWD and attempted an upload, but that didn't result in an error notification

Would it be best for me to create separate issues for these?

**Comment by marcosnils** [comment]
Did you restart the `site` container after switching to this branch? Since this requires a different version of the SDK, you need to restart it so the `_config.yml` gets reloaded.

**Comment by myitcv** [comment]
I did... but let me just double check.

**Comment by myitcv** [comment]
Ah, it appears to be using `v0.0.4`.

**Comment by myitcv** [comment]
Switched to using `v0.0.7`, but still seeing the same behaviour as above. Let's go through tomorrow

**Comment by marcosnils** [comment]
Fixed #169
