### ISSUE TITLE
guides: unable to complete deployed basic-go-modules-example

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#128]
Steps to reproduce:

* Visit https://play-with-go.dev/basic-go-modules-example/
* Click the first four steps in sequence
* Observe the last command in the second command block fails with:

```
$ git push -u origin main
fatal: unable to access 'https://gopher.live/mod18af785c7bc01.git/': server certificate verification failed. CAfile: none CRLfile: none
```

This suggests to me that that guide container is not routing `gopher.live` to the private nginx instance per the `docker-compose` setup:

https://github.com/play-with-go/play-with-go/blob/bd8be67d0e39d5f97397dc7f95a2b2ba44028f8c/docker/nginx/nginx.conf#L4-L23

In development this happens because we pass set the `PWD_UNSAFE=true` environment variable:

https://github.com/play-with-go/play-with-go/blob/bd8be67d0e39d5f97397dc7f95a2b2ba44028f8c/docker-compose.yml#L88

This causes the guide-configured networks to be passed to PWD (but I'm guessing this doesn't mean anything in our production deploy?)

**Comment by myitcv** [comment]
We will look at this once again once we have the production deployment in place.

**Comment by marcosnils** [comment]
This can be closed, right Paul?

**Comment by myitcv** [comment]
Yep, thanks.
