### ISSUE TITLE
cmd/controller: do not reload guides from disk on each request

### ISSUE THREAD

**Issue by marcosnils** [play-with-go/play-with-go#153]
IIUC this code https://github.com/play-with-go/play-with-go/blob/main/cmd/controller/controller.go#L109 loads the cue config from disk on earch request? 

I'm not very familiarized with cue and not sure if the Go lib actually optimizes this somehow.. but isn't this very slow?

**Comment by myitcv** [comment]
This was an initial version to speed up development. The better way to do this will be to have a timer that attempts a reload asynchronously from any requests every, say, minute. I'll retitle this to capture that.
