### ISSUE TITLE
guides: hard-coding of bold highlighting in code blocks breaks dark mode

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#181]
In normal mode things look fine:

![good_code](https://user-images.githubusercontent.com/3374574/97999046-c03d7680-1de2-11eb-8e2c-c4612d20c966.png)

However, in dark mode things "disappear":

![bad_code](https://user-images.githubusercontent.com/3374574/97999084-caf80b80-1de2-11eb-9608-f8ac90eee80f.png)

This is because I am hardcoding the font colour in `preguide`:

https://github.com/play-with-go/preguide/blob/d052385e0a88b18eacc4d617143f383111671a4d/internal/types/guide.go#L316

If someone can please let me know how I should fix this markup, I will fix my own bug 😄

**Comment by marcosnils** [comment]
Fixed by https://github.com/play-with-go/play-with-go/commit/0a29e9aee1525794f59b1770b2faac1ca79c0506
