### ISSUE TITLE
ui: remove Import button (for now)

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#2]
### What is the URL of the page with the issue?

http://localhost:4000/using-go-modules/

### What is your user agent?

<pre>
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.23 Safari/537.36
</pre>

### Screenshot

![drop_import_button](https://user-images.githubusercontent.com/3374574/80334137-349dc880-8848-11ea-8205-7368f1cdf1d3.png)

### What did you do?

Visited the above page.

### What did you expect to see?

No "Import" button

### What did you see instead?

The "Import" button.

We can (and should) provide something like this down the line, but initially I think it makes sense to strip things back because it is not essential to import anything in order to complete a guide.

**Comment by marcosnils** [comment]
Should be fixed by #155
