### ISSUE TITLE
style: font differences within a page

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#204]
It appears like we have font differences between various elements on a page:

![bad_font](https://user-images.githubusercontent.com/3374574/98503334-20ea0a80-224c-11eb-97ac-748661cce23c.png)

**Comment by myitcv** [comment]
Close 😄 

![Screen Shot 2020-11-12 at 06 03 56](https://user-images.githubusercontent.com/3374574/98902076-e7fca080-24ac-11eb-8548-5f2e4d2c8cc4.png)

* Looks like a small size difference still (my browser reports a 1px diff)
* The alignment of the numbers also looks a bit weird?

The second of these points is, however, very minor

**Comment by marcosnils** [comment]
Found the problem withe the font size. Couldn't find the reason for the misalignment, will check tomorrow!
