### ISSUE TITLE
guides: prestep credentials not being passed to instance, or wrong backend version?

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#215]
For example, try and go through the steps of https://play-with-go.dev/retracting-module-versions_go116_en/.

When it comes to step 4, you get:

```
$ git push -q origin main
Username for 'https://gopher.live': 
```

Which indicates either:

* the credentials have not been passed by the SDK when creating the instance, or
* the backend is the wrong version
* something else 😄

**Comment by myitcv** [comment]
I've just confirmed the prestep is returning values... so it appears that the backend is simply ignoring these values. Could be the wrong version deployed?

**Comment by marcosnils** [comment]
Fixed.
