### ISSUE TITLE
guides: inline monospace font appears smaller than surrounding text

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#229]
As noticed by @mvdan 

![20201111_12h04m50s_grim](https://user-images.githubusercontent.com/3374574/98810026-71ad5f00-2416-11eb-976a-7dde752300bf.png)

As of https://github.com/play-with-go/play-with-go/commit/b81b7c7ebd28cbdc89a5eb3e532922f663282b40

**Comment by marcosnils** [comment]
Fixed by a4d42cecb2986d13b7e01621bd0b4cabb2e04a54
