### ISSUE TITLE
Landing page gopher looks a bit pixelated on high-DPI screens

### ISSUE THREAD

**Issue by mvdan** [play-with-go/play-with-go#234]
For example, see the screenshot below, taken on my 1440p monitor at 1x scaling, but zoomed in at 200% to compensate:

![20201111_12h52m35s_grim](https://user-images.githubusercontent.com/3576549/98813999-f9966780-241c-11eb-97f0-e3c5f382bb35.png)

I would usually run at about 150% zoom instead, but 200% makes the pixelation even clearer when compared to the sharp text.

Since the gopher eyes and snout are really just line drawings with flat colors, it would be best to use an SVG instead, which will be lighter and scale perfectly like the text. Otherwise, perhaps try to get a higher-resolution PNG to be able to scale to 2x without noticeable pixelation.

**Comment by mvdan** [comment]
I should note that, on the GitHub UI, the text on the left side of the screenshot  looks a bit pixelated too. This is just because GitHub renders the cropped screenshot bigger than it actually is. The original text isn't pixelated at all.

**Comment by marcosnils** [comment]
Fixed by a4d42cecb2986d13b7e01621bd0b4cabb2e04a54
