### ISSUE TITLE
guides: font weight is too great in a blockquote

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#241]
e.g. considering the https://play-with-go.dev/retracting-module-versions_go116_en/ guide:

![Screen Shot 2020-11-11 at 21 40 18](https://user-images.githubusercontent.com/3374574/98867507-929da080-2466-11eb-9faa-16146be8b11b.png)

Simply using the same font weight appears to work well:

![Screen Shot 2020-11-11 at 21 41 36](https://user-images.githubusercontent.com/3374574/98867584-b7921380-2466-11eb-9bbc-37b2b76b5a6b.png)

**Comment by marcosnils** [comment]
Fixed by a4d42cecb2986d13b7e01621bd0b4cabb2e04a54
