### ISSUE TITLE
site: landing page strap line shows in yellow instead of white - intentional?

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#244]
![Screen Shot 2020-11-12 at 06 10 52](https://user-images.githubusercontent.com/3374574/98902580-e8496b80-24ad-11eb-9e7d-1cd6c40ee856.png)

I'm fairly sure the "Hands-on, interactive tutorials for programming in Go." used to be white?! 

To my untrained, design un-aware eye, white text (or whatever colour it is) perhaps looks a bit better/sharper? Having the main title as yellow still works really well though.

That said, I entirely defer to @denreyrey on the final answer :) 

FYI @marcosnils

**Comment by marcosnils** [comment]
AFAIK they are since I believe Den said that white was a bit "boring". Will check with her later :)
