### ISSUE TITLE
Logo on sign-in

### ISSUE THREAD

**Issue by denreyrey** [play-with-go/play-with-go#257]
When connecting to Github, the image is a gopher; need to change that for Go Logo
![image](https://user-images.githubusercontent.com/15708729/98953925-075ef200-24dc-11eb-8cbc-a37414b58ebf.png)

**Comment by marcosnils** [comment]
cc @myitcv shall we use the landing image?

**Comment by myitcv** [comment]
I'll leave it up to you!

**Comment by myitcv** [comment]
Fixed.
