### ISSUE TITLE
site: wrong "link" icon for play-with-go.dev pages?

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#280]
I've got no idea what this is called, but the following screenshot of a tweet I was drafting shows the issue:

![Screen Shot 2020-11-13 at 10 50 28](https://user-images.githubusercontent.com/3374574/99064639-232acc80-259e-11eb-8630-ab86476d1f95.png)

How/where do we change from the brown gopher to something else?!

@denreyrey @marcosnils - your expertise required!

**Comment by marcosnils** [comment]
Weird.. this works on the twitter card validator page. 
![image](https://user-images.githubusercontent.com/1578458/99072198-523b4100-2592-11eb-8a5b-669594f9b320.png)

I've changed this yesterday so maybe it's a cache issue?

**Comment by myitcv** [comment]
Weird. It's working for me now!
