### ISSUE TITLE
guides: Can't quit vi from Firefox

### ISSUE THREAD

**Issue by mbroshi** [play-with-go/play-with-go#337]
**Describe the bug**
The escape key is not working in Firefox when editing a file in vi.

**To Reproduce**
1. Go to https://play-with-go.dev/get-started-with-go_go115_en/ using Firefox
2. Type vi hello.go at the command prompt
3. Type "i"
4.  Type the contents of hello.go
5. Type "Esc" to exit edit mode
6. Type "wq" and "Enter"

If I am on Firefox, step 5 fails, and I cannot exit edit mode to save my file. In Chrome, the Esc key works.

**Expected behavior**
Step 5 succeeds and I exit edit mode.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 83.0

**Comment by myitcv** [comment]
Interesting. I've just confirmed that things are working with:

* Firefox 83.0 (64-bit)
* macOS 10.12.6 (I know, old!)

But also with:

 * OS: Ubuntu 20.04
 * Browser: Firefox
 * Version: 83.0

i.e. exactly your setup. 

I'm wondering what to look at next.

@marcosnils - any ideas?

**Comment by marcosnils** [comment]
Works here also. Debian buster and Firefox 83.0 as well.

Can you confirm that `esc` as actually being sent to the terminal? If you open your network inspector plugin and you check the websocket messages, you should see that the ESC keycode should be sent to the backend when you press it. If that's not the case, then it's probably something on the browser that's preventing it.

**Comment by mbroshi** [comment]
Well, isn't that ironic: It was my Vimium plugin that was intercepting the `esc` key! Thanks for the triage help @marcosnils
