### ISSUE TITLE
[HELP] - Can not Login

### ISSUE THREAD

**Issue by Nishan8583** [play-with-go/play-with-go#370]
**Can not Login**
On the right side of each tutorial, where login with gmail/github is located, non clickable button, just images.

**To Reproduce**
1. Go to 'any topic'
2. Click on 'sign in with ... options'

**Expected behavior**
To be able to sign in

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [chrome,firefox,brave]

**Comment by myitcv** [comment]
Hi @Nishan8583 - sorry to hear you're having trouble. Clicking on either of the options:

![Screen Shot 2021-04-28 at 13 45 01](https://user-images.githubusercontent.com/3374574/116405804-f73b9480-a827-11eb-982a-9adc8e5bb89e.png)

should popup a window that allows you to complete the sign-in process. e.g. when I click on "Sign-in with Google" I see the following popup:

![Screen Shot 2021-04-28 at 13 45 55](https://user-images.githubusercontent.com/3374574/116406114-3e298a00-a828-11eb-8594-0acf797df3e2.png)

Are you seeing that window popup?

**Comment by Nishan8583** [comment]
No, I can not click on it. Its just an image from my end for some reason. When i inspect it in browser only image tag there.

**Comment by myitcv** [comment]
@marcosnils - any ideas what might be going on here?

**Comment by marcosnils** [comment]
> should popup a window that allows you to complete the sign-in process. e.g. when I click on "Sign-in with Google" I see the following popup:

I was about to highlight the same thing here. Are you sure you don't have an ad-blocker that might be conflicting?

**Comment by marcosnils** [comment]
![image](https://user-images.githubusercontent.com/1578458/116409456-3ce96480-a80a-11eb-8736-27edec212c1a.png)


As you can see it's not an image. It's an HTML button.

**Comment by jalil** [comment]
@Nishan8583 Make sure the gopher image is not covering the login page buttons.  IF its covering the buttons you will not be able to select either of them to login.

**Comment by marcosnils** [comment]
> @Nishan8583 Make sure the gopher image is not covering the login page buttons. IF its covering the buttons you will not be able to select either of them to login.

Hmm good point, I'll check this out today.

**Comment by myitcv** [comment]
I could repro something similar when the Gopher was lurking over the top of the buttons FWIW!
